server:
  port: 8000
dubbo:
  scan:
    base-packages: com.alibaba.cloud.dubbo.provider.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
spring:
  application:
    name: dubbo-spring-cloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  main:
    allow-bean-definition-overriding: true
